        typography = Typography.copy(
            titleLarge = Typography.titleLarge.copy(fontFamily = FontFamily.SansSerif),
            titleSmall = Typography.titleSmall.copy(fontFamily = FontFamily.SansSerif),
            titleMedium = Typography.titleMedium.copy(fontFamily = FontFamily.SansSerif),
            headlineMedium = Typography.headlineMedium.copy(fontFamily = FontFamily.SansSerif),
            headlineLarge = Typography.headlineLarge.copy(fontFamily = FontFamily.SansSerif),
            headlineSmall = Typography.headlineSmall.copy(fontFamily = FontFamily.SansSerif),
            bodyLarge = Typography.bodyLarge.copy(fontFamily = FontFamily.SansSerif),
            bodySmall = Typography.bodySmall.copy(fontFamily = FontFamily.SansSerif),
            bodyMedium = Typography.bodyMedium.copy(fontFamily = FontFamily.SansSerif),
            displayLarge = Typography.displayLarge.copy(fontFamily = FontFamily.SansSerif),
            displaySmall = Typography.displaySmall.copy(fontFamily = FontFamily.SansSerif),
            displayMedium = Typography.displayMedium.copy(fontFamily = FontFamily.SansSerif),
            labelLarge = Typography.labelLarge.copy(fontFamily = FontFamily.SansSerif),
            labelSmall = Typography.labelSmall.copy(fontFamily = FontFamily.SansSerif),
            labelMedium = Typography.labelMedium.copy(fontFamily = FontFamily.SansSerif),
        )
